### ISSUE TITLE
Upgrade to latest Eclipse Release

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#1]
Currently we are using Eclipse-Neon as a base platform for ChemClipse, in the meantime (more than three years have passed by) there are several new releases with many bug fixes and improvements.
We should try to upgrade at least to the [2019-06 (Current release)](https://wiki.eclipse.org/Simultaneous_Release) release.

**Comment by laeubi** [comment]
This is blocked by #8 as we encountered crashes with some OpenJDK/FX versions related to JavaFX views.

**Comment by eselmeister** [comment]
A migration to the latest Eclipse release is highly desired. Unfortunately, some issues are blocking this task:

#8 - JavaFX: the 3D part needs to be replaced by a similar, Eclipse compliant solution
#536 - java.xml: the package needs to be replaced by an alternative
#535 - JRE: the latest JRE shall be used

SWTChart:
[#166](https://github.com/eclipse/swtchart/issues/166) - GTK3 and SWT Display error
[#150](https://github.com/eclipse/swtchart/issues/150) - macOS Buffer Selection Error

**Comment by eselmeister** [comment]
Done
