### ISSUE TITLE
Measurement-Results should be visualized inside Chromatogram

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#101]
Currently the data flow is just from Chromatogram > Measurements Results. A user can the select items and probably update other views (e.g. the Scan-Comparision-View). 
In some cases it would be good if the result would be able to contribute a Visual feedback into the chromatogram (e.g. peaks or areas affected by the current selection).

**Comment by eselmeister** [comment]
From my point of view, this could be relative easily resolved, as soon as we have refactored the chromatogram selection event handling in ChemClipse. We still have problems, that some list are not updated or that the chromatogram editor is not updated if one has removed peak(s) from the scan/peak list and so on. I think it is worth to have a look at the event processing in ChemClipse first, which might solve this problem partly.

**Comment by laeubi** [comment]
requires https://github.com/eclipse/swtchart/issues/77
