### ISSUE TITLE
Signal Value in Scan Chart and Scan Table maxes out at fixed value

### ISSUE THREAD

**Issue by lorenzgerber** [eclipse-chemclipse/chemclipse#1100]
The Signal Value in Scan Chart and Scan Table maxes out at 2'147'483'647. This seems a pure visualisation issue and does not affect internal calculations.  
![Screenshot 2022-08-08 at 16 23 54](https://user-images.githubusercontent.com/3002206/183440993-591fa26d-23c9-4931-9d81-2afd87919e93.png)
 
![Screenshot 2022-08-08 at 16 17 54](https://user-images.githubusercontent.com/3002206/183440353-3d4a54e3-f9a9-4168-8ceb-2c8d11bf4cae.png)

**Comment by Mailaender** [comment]
Strange that it is `Integer.MAX_VALUE`.

**Comment by eselmeister** [comment]
The user can define whether to display the area with or without decimals:

![Screenshot from 2022-08-09 07-25-13](https://user-images.githubusercontent.com/686671/183571253-edb4de7b-6a3c-405d-80db-8c1c8c2e5cc8.png)

In case of "without", a cast to integer is used. Indeed, if values are higher than Integer.MAX_VALUE, this approach fails. DecimalFormat could be used instead. The same approach could be used for the mentioned "Signal" display.

**Comment by lorenzgerber** [comment]
> The user can define whether to display the area with or without decimals:
> 
> ![Screenshot from 2022-08-09 07-25-13](https://user-images.githubusercontent.com/686671/183571253-edb4de7b-6a3c-405d-80db-8c1c8c2e5cc8.png)
> 
> In case of "without", a cast to integer is used. Indeed, if values are higher than Integer.MAX_VALUE, this approach fails. DecimalFormat could be used instead. The same approach could be used for the mentioned "Signal" display.

Above case with Peak Areas is unrelated and currently not a problem (not limited by Integer.MAX_VALUE, solved with labels in PeakScanListLabelProvider):  
```
if(PreferenceSupplier.showAreaWithoutDecimals()) {
					DecimalFormat integerFormat = getIntegerDecimalFormatInstance();
					text = integerFormat.format(peak.getIntegratedArea());
				} else {
					text = decimalFormat.format(peak.getIntegratedArea());
				}
```
