### ISSUE TITLE
Add Filter: Scan Duplicator

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#1104]
Sometimes, the scan rate of a chromatogram is quite low. In such a case, a scan duplicator shall be available to duplicate the amount of scans, hence to increase the scan density. When applying a Savitzgy-Golay filter afterwards, reasonable results can be generated.

**Comment by eselmeister** [comment]
![Screenshot from 2022-08-17 12-12-16](https://user-images.githubusercontent.com/686671/185094733-b05a4608-2b37-4f53-987c-be457d385393.png)

![Screenshot from 2022-08-17 12-12-33](https://user-images.githubusercontent.com/686671/185094738-669007af-c1d7-40dd-a2ba-7717dc948cbd.png)

![Screenshot from 2022-08-17 12-12-52](https://user-images.githubusercontent.com/686671/185094743-dd6176a8-0781-49d9-b50f-fee0e20b23d7.png)

![Screenshot from 2022-08-17 12-15-25](https://user-images.githubusercontent.com/686671/185094748-fc4a2bbc-bff5-4ba6-a457-32b32863c4cd.png)

**Comment by Mailaender** [comment]
Why does it say merge scans when this should duplicate them?

**Comment by eselmeister** [comment]
In the middle of the current and the next scan, a new scan is created. In case of MSD, merge scans creates a mixed scan of both m/z values of the current and the next scan. The same is done with WSD data.
