### ISSUE TITLE
Support Procedures in the processing API

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#120]
Currently we can execute Methods, butt these are always working on the same input data.
What is missing is something like a procedure/function call where one can transform the data in some way, pass it down to an execution pipeline and then proceed with the original data set.
Whether or not this has influence on the data itself will not be restricted, for example a workflow might work like this:

- A ChromatogramSelection is processed by some processors
- then a Procedure reads a chromatogram from a file, process it with some sub-steps and link that chromatogram with the original one by putting it to the ReferencedChromatograms
- now other steps can follow working on the original chromatogramselection enhanced by the Reference Chromatogram

Another workflow might do the following:
- A ChromatogramSelection is processed by some processors
- Then a procedure extracts a given Reference Chromatogram (e.g. always index 1) and write it to a file
- now other steps that follow will still see the original chromatogramselection without any changes

To keep things simple an clear, we won't allow a procedure to actually change the type of data processed (this will be the are of a Transformer), so procedures are just a way to branch out the processing of the same type to perform some substeps, but for example do not allow to convert a Chromatogram to a peaklist and then process on peaklists.

**Comment by kerner1000** [comment]
> then a Procedure reads a chromatogram from a file, process it with some sub-steps and link that chromatogram with the original one by putting it to the ReferencedChromatograms

It would also be useful if it would be possible to open a new chromatogram editor based on another chromatogram selection or modified chromatogram.

**Comment by laeubi** [comment]
This is tracked here: https://github.com/eclipse/chemclipse/issues/99
