### ISSUE TITLE
Reduce the complexity of the application 

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#1393]
In the early days, a support to handle command line options has been added. This was a good test case, but have increased the complexity to maintain the source code. Furthermore, the reference to the UI bundle is set in the plugin.xml via the extension point mechanism. The existing extension point shall be migrated to OSGi DS. Another problem with this approach was, that the UI extension point was referenced in the model bundle, which worked as it only was a text reference in the plugin.xml, but it was less optimal.

**Comment by Mailaender** [comment]
You didn't remove https://github.com/eclipse/chemclipse/blob/951bd02c5866ee716f874b2d0a6d8789b1bee20b/chemclipse/products/org.eclipse.chemclipse.rcp.compilation.community.product/chemclipse.compilation.community.product#L25

**Comment by eselmeister** [comment]
Thanks for the hint. Will be fixed.
