### ISSUE TITLE
org.eclipse.ui.console should be not used in the model bundle

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#1430]

**Comment by Mailaender** [comment]
Why?

**Comment by eselmeister** [comment]
If the logger shall be re-used in an environment without graphical user interface, the UI dependency could not be started. That's why model and UI have been strictly separated in ChemClipse. If the org.eclipse.ui.console bundle is needed, it shall be placed in a UI bundle, e.g.

`org.eclipse.chemclipse.logging.ui`

**Comment by Mailaender** [comment]
Yes, I see. Apparently, the dependency is unused. Your title and no description was misleading.
