### ISSUE TITLE
Provide an UI to install system methods

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#154]
To install a user-system-wide method (regardless of user settings), the file must be copied to the right location, we should provide a menu-item "Install Custom Processing Method" that allows to select a file (e.g. revived by mail) that is then copied to the right place. We might impose some restrictions on the type of method, e.g. that it must be finalized, has a category and so on, configurations and even bundles could be installed that way.

**Comment by laeubi** [comment]
We should even offer to install plugins/dropins via a wizzard + option to easy uninstall it.

**Comment by laeubi** [comment]
![grafik](https://user-images.githubusercontent.com/1331477/88391772-1ac64000-cdbb-11ea-953f-4dba2ad47de0.png)

**Comment by eselmeister** [comment]
@laeubi This seems to be broken under Linux. Nothing happens after clicking on the "Install Assets" button:

![Bildschirmfoto vom 2020-07-24 16-15-24](https://user-images.githubusercontent.com/686671/88400769-17d24c00-cdc9-11ea-909d-753b38c466a2.png)

**Comment by eselmeister** [comment]
@laeubi Have you tested it also on macOS and Linux?

**Comment by laeubi** [comment]
I have tested this with ChemClipse  Copmmunity product edition under Linux. that's where the screenshot is taken from.

**Comment by laeubi** [comment]
Also downloaded https://ci.eclipse.org/chemclipse/job/chemclipse/job/develop/lastSuccessfulBuild/artifact/chemclipse/products/org.eclipse.chemclipse.rcp.compilation.community.product/target/products/org.eclipse.chemclipse.rcp.compilation.community.product.id-linux.gtk.x86_64.tar.gz right now and it works also, do you see any exceptions in the log?

**Comment by laeubi** [comment]
I have tested with OpenChrom Community edition and can see that there is nothing happening, so it seems it is related to OpenChrom --> OpenChrom/openchrom#73

**Comment by eselmeister** [comment]
@laeubi ChemClipse and its upstream products are not decoupled. Hence, please behave like a professional and don't just say it's a problem of others.

**Comment by eselmeister** [comment]
@laeubi If upstream products like to use it, is there anything that needs to be added in the product configuration?

**Comment by laeubi** [comment]
@eselmeister  It still needs to be investigated and fixed there, and I never said its someones else problem so whats the problem?
Closing/reopening tickets without any idea what or where it is wrong doesn't make sense.

**Comment by eselmeister** [comment]
@ all others:
If one likes to use Christophs functionality without ending in a broken link, you have to add the following entry in the "Start Levels" definition of your product:
`
<plugin id="org.eclipse.equinox.cm" autoStart="true" startLevel="2" /> `

**Comment by laeubi** [comment]
See https://github.com/OpenChrom/openchrom/commit/800abf70dda0bcf77e9bbae69c3cf843e92b3f5f

**Comment by laeubi** [comment]
Menu item is now disabled when prerequisites are not meet (e.g. config service currently not started).
