### ISSUE TITLE
IMarkedIons Mode inverted?

### ISSUE THREAD

**Issue by kerner1000** [eclipse-chemclipse/chemclipse#173]
Taking a look at [AbstractScanMSD#removeIons](https://github.com/eclipse/chemclipse/blob/89e60400a7ea7127d7b39379704832a8e07f2318/chemclipse/plugins/org.eclipse.chemclipse.msd.model/src/org/eclipse/chemclipse/msd/model/core/AbstractScanMSD.java#L253)

```
@Override
	public AbstractScanMSD removeIons(IMarkedIons markedIons) {

		if(markedIons == null) {
			// TODO maybe log warning?
			return this;
		}
		//
		Set<Integer> nominalIons = markedIons.getIonsNominal();
		IonMarkMode mode = markedIons.getMode();
		switch(mode) {
			case INCLUDE:
				/*
				 * Remove all listed ions.
				 */
				removeIons(nominalIons);
				break;
			case EXCLUDE:
				/*
				 * Remove all except the listed ions.
				 */
				Set<Integer> removeIons = new HashSet<>();
				for(IIon ion : ionsList) {
					int nominal = AbstractIon.getIon(ion.getIon());
					if(!nominalIons.contains(nominal)) {
						removeIons.add(nominal);
					}
				}
				removeIons(removeIons);
				break;
			default:
				/*
				 * Do nothing
				 */
				break;
		}
		//
		return this;
	}
```
The include case removes all given ions, the exclude case removes all ions except the given ones.
For me, this looks like inverted logic. I think it should look rather somewhat like this:
```
@Override
	public AbstractScanMSD removeIons(IMarkedIons markedIons) {

		if(markedIons == null) {
			// TODO maybe log warning?
			return this;
		}
		//
		Set<Integer> nominalIons = markedIons.getIonsNominal();
		IonMarkMode mode = markedIons.getMode();
		switch(mode) {
			case EXCLUDE:
				/*
				 * Remove all listed ions.
				 */
				removeIons(nominalIons);
				break;
			case INCLUDE:
				/*
				 * Remove all except the listed ions.
				 */
				retainIons(nominalIons);
				break;
			default:
				/*
				 * Do nothing
				 */
				break;
		}
		//
		return this;
	}
```

Another example of unintuitive logic:
[MassSpectrum_20_Test](https://github.com/eclipse/chemclipse/blob/a978e53d169b628159fec58de6e2afdc9622a623/chemclipse/plugins/org.eclipse.chemclipse.msd.model.fragment.test/src/org/eclipse/chemclipse/msd/model/implementation/MassSpectrum_20_Test.java#L46)

```
@Override
	protected void setUp() throws Exception {

		super.setUp();
		massSpectrum = new ScanMSD();
		ion = new Ion(45.5f, 78500.2f);
		massSpectrum.addIon(ion);
		ion = new Ion(104.1f, 120000.4f);
		massSpectrum.addIon(ion);
		ion = new Ion(32.6f, 890520.4f);
		massSpectrum.addIon(ion);
		ion = new Ion(105.7f, 120000.4f);
		massSpectrum.addIon(ion);
		ion = new Ion(28.2f, 33000.5f);
		massSpectrum.addIon(ion);
		excludedIons = new MarkedIons(IMarkedIons.IonMarkMode.INCLUDE);
	}

	@Override
	protected void tearDown() throws Exception {

		massSpectrum = null;
		ion = null;
		excludedIons = null;
		super.tearDown();
	}

	public void testGetTotalSignal_1() {

		assertEquals("getTotalSignal", 1242021.9f, massSpectrum.getTotalSignal());
	}

	public void testGetTotalIonSignal_2() {

		excludedIons.add(new MarkedIon(104));
		assertEquals("getTotalSignal", 1122021.5f, massSpectrum.getTotalSignal(excludedIons));
	}
```

The MarkedIon object is initialized with `IonMarkMode.INCLUDE`, but in the total signal calculation, it is expected that those intensities are *not* considered but instead only all other ion intensities.

**Comment by laeubi** [comment]
The meaning of include/exclude depend on the function and should/must be documented there. In your example, removing ions from a scan as mentioned in the comments it has the following meaning:
 
- INCLUDE: All Ions **included** in the list are removed
- EXCLUDE : All Ions **not included** in the list are removed

this can have different meanings for other usage scenarios and are just matter of definition, for example a method that extracts certain ions from a spectra might use 

- INCLUDE for all ions to **keep**
- EXCLUDE for all ions to **ignore**

**Comment by eselmeister** [comment]
The marked ions construct needs to be handled with care. It works fine as it is at the moment.
