### ISSUE TITLE
Peak/Scan Labels - no text offset with inverted triangle

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#185]
Previous versions of OpenChrom had space between the peak/scan marker and the label. This was introduced for a better readability:

![OpenChrom-1 3 0](https://user-images.githubusercontent.com/686671/71544694-fddfa080-2982-11ea-830a-edfbff3fbe60.png)

The current version doesn't show any space between peak/scan marker and the label, thus it is harder to read the labels.

![Bildschirmfoto von 2019-12-28 14-08-19](https://user-images.githubusercontent.com/686671/71544717-1d76c900-2983-11ea-8890-c703b3c22ff0.png)

**Comment by eselmeister** [comment]
The problem still exists. It seems that it has been introduced with the rotation and collision options. It works well with a previous version:

![Bildschirmfoto von 2019-12-29 20-57-53](https://user-images.githubusercontent.com/686671/71561964-f81ab580-2a7d-11ea-853b-203c8aabafde.png)

The current version in debug modus shows the following ranges:

![Bildschirmfoto von 2019-12-29 21-02-38](https://user-images.githubusercontent.com/686671/71562051-a58dc900-2a7e-11ea-8340-59d69797696c.png)

![Bildschirmfoto von 2019-12-29 21-02-47](https://user-images.githubusercontent.com/686671/71562052-a9b9e680-2a7e-11ea-8d6d-d857ea6c8f94.png)

**Comment by laeubi** [comment]
The problem is that currently the background value of a peak is not taken into account when painting the labels.

**Comment by eselmeister** [comment]
Perfect. I'm happy again.
