### ISSUE TITLE
DataExplorer should also provide a view to the Workspace

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#187]
Currently the DataExplorer shows:

- Drives
- Home
- User-Location

but we also have a concept of "Workspace" where projects are located in. These can currently only be accessed via the 'ProjectExplorer'. We should therefore provide a new tab named 'projects' that list all workspace projects/locations and allows to open files from there.

When this is done, we should decide what functionality of project-explorer is still required and maybe integrate this in the Data-Explorer view so we can on the long term get rid of the ProjectExplorer.

**Comment by laeubi** [comment]
The following features of ProjectExplorer are currently missing in DataExplorer but could be useful anyways:

- copy/paste/delete/move operations
- creating new items via wizard in selected location
- ... ?

**Comment by Mailaender** [comment]
Reverse duplicate of https://github.com/eclipse/chemclipse/issues/437.
