### ISSUE TITLE
Remove org.eclipse.chemclipse.model.core.IScan.getTimeSegmentId()

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#190]
It seems this is only used in unit-test. As it is also not documented what this is useful for we should consider removing this from the API

**Comment by kerner1000** [comment]
+1

**Comment by eselmeister** [comment]
-1Time segments are needed to handle specific TandemMS data structures. Removing them would break some converter code.Am 03.01.2020 19:23 schrieb Christoph Läubrich <notifications@github.com>:It seems this is only used in unit-test. As it is also not documented what this is useful for we should consider removing this from the API
