### ISSUE TITLE
Remove org.eclipse.chemclipse.model.core.IScan.getParentChromatogram()

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#191]
It seems there is no use for this method in the chemclipse codebase. If we need such functionality in some rare case we can better implement this using the adapter pattern.

**Comment by kerner1000** [comment]
+1

**Comment by eselmeister** [comment]
Please double check the codebase to not break existing functionalities.The chromatogram holds a list of scans and peaks. Relation is clear in this case.Scans and peaks could be handled separately or as part of a chromatogram. We should think about technical solutions to ask a scan or peak if it has a parent chromatogram.Am 03.01.2020 19:25 schrieb Christoph Läubrich <notifications@github.com>:It seems there is no use for this method in the chemclipse codebase. If we need such functionality in some rare case we can better implement this using the adapter pattern.
