### ISSUE TITLE
Remove org.eclipse.chemclipse.model.core.IScanSerializable

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#192]
It just extends Serializeable and no-one really uses that type

**Comment by eselmeister** [comment]
Serialization has been used to support the do/redo/undo functionality when running filters etc.. As this concept was never really used, serializable is probably not needed any longer. Please have a look at do/redo ... functions before removing it.Am 03.01.2020 19:26 schrieb Christoph Läubrich <notifications@github.com>:It just extends Serializeable and no-one really uses that type
