### ISSUE TITLE
Remove getRetentionTimeColumn1/2 from IScan interface

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#193]
From the javadoc this is used in "GCxGC or LCxLC applications", so we should not place this in the generic IScan interface.

**Comment by kerner1000** [comment]
I not sure about this one. Why should GCxGC be handled differently than 'simple' GC?
I would rather support an arbitrary number of retention times. A simple GC could have just "column[0]", GCxGC column[1], GCxGCxGC column[2] and so forth.

**Comment by laeubi** [comment]
It should not be handled differently but we should think about better ways to represent it (maybe like you described) instead of adding colum3, colum4, columX methods... some time as it blows up the interface. The main problem is that a 'single GC' has to implement this methods with dummy values and a consumer of the IScan-interface can't know that these are just dummy values.

Maybe we even can make it that way that a scan can reference some kind of parent/child relation
