### ISSUE TITLE
Peak Filter: Area%

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#196]
Add a filter to

- disable (set "Active for Analysis": false)
- delete

peaks, if certain area% constraints are matched (0-100%):

- Min Area%
- Max Area%

![demo-peak-filter](https://user-images.githubusercontent.com/686671/71830730-a7234680-30a7-11ea-9a1f-ee7b087198fb.png)

See peak filter examples in:

- org.eclipse.chemclipse.chromatogram.xxd.edit.supplier.snip.core.PeakFilter
- org.eclipse.chemclipse.xxd.model.filter.peaks.RemoveAllPeaksFilter
- ...

**Comment by laeubi** [comment]
@alexstark4 is there anything left to do here?
