### ISSUE TITLE
Peak Filter: Leading/Tailing

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#197]
Add a filter to

- disable (set "Active for Analysis": false)
- delete

peaks, if certain leading/tailing constraints are matched:

- Min/Max Leading
- Min/Max Tailing

![demo-peak-filter](https://user-images.githubusercontent.com/686671/71830866-f79aa400-30a7-11ea-9240-a5253325c281.png)

See peak filter examples in:

- org.eclipse.chemclipse.chromatogram.xxd.edit.supplier.snip.core.PeakFilter
- org.eclipse.chemclipse.xxd.model.filter.peaks.RemoveAllPeaksFilter
- ...

**Comment by laeubi** [comment]
@alexstark4 is there anything left to do here?
