### ISSUE TITLE
Peak Filter: Width

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#198]
Add a filter to

- disable (set "Active for Analysis": false)
- delete

peaks, if certain width constraints are matched:

- Min Width
- Max Width / Unlimited

![demo-peak-filter](https://user-images.githubusercontent.com/686671/71830955-2b75c980-30a8-11ea-8a63-58eced11674f.png)

See peak filter examples in:

- org.eclipse.chemclipse.chromatogram.xxd.edit.supplier.snip.core.PeakFilter
- org.eclipse.chemclipse.xxd.model.filter.peaks.RemoveAllPeaksFilter
- ...

**Comment by alexstark4** [comment]
I have difficulties to find in the model where and how exactly the values are calculated that are displayed as can be seen in the picture above. None of the getWidth*() methods from the peak model returns such a value.

Could you kindly give me a hint where to look for it?

**Comment by laeubi** [comment]
@alexstark4 is there anything left to do here? @kerner1000
