### ISSUE TITLE
[FirstDerivative] detect peaks on multiple traces

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#212]
Currently one can specify ions the PeakDetotor works on instead of the TIC what is equal to an ion filtered Chromatogram.
Another usecase would be to detect on each ion-trace individually e.g on trace 20, 102 and 149, this should work as if the user has first called the detector with parameter ion = 20, then ion = 102 , .... and so on

**Comment by laeubi** [comment]
User can now select "use individual traces" to detect each iontrace individually.
![grafik](https://user-images.githubusercontent.com/1331477/72065793-55650100-32df-11ea-9f44-ff61f695f4cf.png)

**Comment by eselmeister** [comment]
Smart! :-)
