### ISSUE TITLE
Support Min/Max for CompositeView-Editors like PCA

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#22]
Composite MultiViews could leverage the min/max feature for traditional views inside ChemClipse.

This is currently blocked by #1 as the MinMaxAddon of the current (old eclipse) version does not behave nice in nested context. Maybe we also need to tune the MinMaxAddon what is not possible for older releases.

**Comment by eselmeister** [comment]
All PCA parts have been refactored. Nested composite editors shouldn't be used as their parts can't be placed on different screens. Having separated parts, drag&drop works out-of-the-box.

https://github.com/eclipse/chemclipse/commit/68bf3743ed7dea6db6c848b9e7fe2a04243e7d7b
