### ISSUE TITLE
Add Peak Traces Part

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#234]
Add a part which automatically extracts and displays the n highest traces of a peak. Each peak stores a peak maximum scan, which could be a mass spectrum. The n highest m/z values shall be used to extract the traces from the underlying chromatogram.

**Comment by eselmeister** [comment]
![Bildschirmfoto von 2020-01-26 14-43-54](https://user-images.githubusercontent.com/686671/73136256-c92b3b80-404b-11ea-8e50-1c4a24a2056c.png)

**Comment by eselmeister** [comment]
![Bildschirmfoto von 2020-01-26 14-44-06](https://user-images.githubusercontent.com/686671/73136275-0db6d700-404c-11ea-814f-4568bfafbac1.png)

**Comment by eselmeister** [comment]
![Bildschirmfoto von 2020-01-26 14-44-15](https://user-images.githubusercontent.com/686671/73136276-1a3b2f80-404c-11ea-952e-a4631d6b4170.png)

**Comment by eselmeister** [comment]
![Bildschirmfoto von 2020-01-26 14-44-39](https://user-images.githubusercontent.com/686671/73136280-2626f180-404c-11ea-9ed8-8f70a7adf669.png)

**Comment by laeubi** [comment]
I think it would be good if we add new UI-Parts that we also add a wiki-page where we describe what the part is for how it could be used, whats the difference to the "Peak Chart"  and so on, wdyt @eselmeister @kerner1000 ?

**Comment by eselmeister** [comment]
The peak chart is intended to show the peak (width, tangents, ...). The traces chart is focused to display the extracted traces. It's separated, otherwise it's getting too complex IMHO.Am 27.01.2020 12:41 schrieb Christoph Läubrich <notifications@github.com>:I think it would be good if we add new UI-Parts that we also add a wiki-page where we describe what the part is for how it could be used, whats the difference to the "Peak Chart"  and so on, wdyt @eselmeister @kerner1000 ?
