### ISSUE TITLE
Retain Zoom in chromatogram overlay, SIC Mode

### ISSUE THREAD

**Issue by lorenzgerber** [eclipse-chemclipse/chemclipse#240]
Currently, when adding new or removing ions in the SIC mode, the zoom always returns to full chromatogram view.

In many cases, the analyst looks at a specific peak by zooming in when using SIC. Adding/removing ions should not return to full chromatogram view, but retain the current zoom.

**Comment by laeubi** [comment]
There is now a little icon in the upper right where the user can lock the current zoom level
![grafik](https://user-images.githubusercontent.com/1331477/73530257-686b7c80-4418-11ea-9325-ec789f61002e.png)
