### ISSUE TITLE
Upgrade to Java 13

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#257]
We are currently facing more and more issues in finding a suitable VM of the JDK8 line e.g. in the area of JavaFX, Eclipse has dropped for example GTK2 support and the Zulu VM we are prefer to use still does not support FX+GTK3.

Also other projects (like SWTChart) are moving on to Java11 we should also prepare for this step ASAP.

**Comment by eselmeister** [comment]
There were problems with JavaFX and GTK3. It seems that this has been fixed in Java 13. It seems to work for Bio7 in combination with AdoptJDK

https://github.com/Bio7/bio7
https://adoptopenjdk.net

Nevertheless, we should be rid of the JavaFX components and replace them by SWT or JOGL if possible.

**Comment by eselmeister** [comment]
Alternatively, we could have a look at the Zulu JDK (with also bundles JavaFX):
https://www.azul.com/downloads/zulu-community

**Comment by laeubi** [comment]
Eclipse will drop Java 8 support by September release so Java 11 will be the minimum requirement:
https://www.eclipse.org/lists/cross-project-issues-dev/msg17532.html
Zulu is working fine from my recent tests and we are already using it for the Java 8 line.

**Comment by eselmeister** [comment]
I will also try to run ChemClipse/OpenChrom against the Zulu JDK (+JavaFX) within the next days. When using Java After Eight, the *.ini file needs to be adjusted. As far as I know, the Java 9+ modules need to be listed:

`--add-modules=ALL-SYSTEM
--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
--module-path=jdk/javafx/lib
--add-modules=javafx.controls,javafx.base,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web
--add-opens=javafx.fxml/javafx.fxml=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.desktop/sun.awt=ALL-UNNAMED
--add-opens=java.desktop/sun.java2d.opengl=ALL-UNNAMED
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.text=ALL-UNNAMED
--add-opens=java.desktop/java.awt.font=ALL-UNNAMED
...`

Let's test it.

**Comment by eselmeister** [comment]
We should also test, that the reports are fully functional after migrating to Java 13+ and AdoptJDK or Zulu JDK. I've seen in a report, that the chromatogram image was black. This could be an issue of Eclipse SWTChart and the Display settings or ChemClipse. It needs further inspection and tests before doing the migration.

**Comment by laeubi** [comment]
This happens when the shell is not rendered (yet) I also have this problem with the current Java8 under Debian 9.

**Comment by eselmeister** [comment]
@laeubi Is there an option in GitHub issues to create something similar to an epic in Jira? We should then collect all issues and potential pitfalls that could occur, when doing a migration to Java 13+.

**Comment by laeubi** [comment]
You can create a "project" or "label" to structure/filter issues.
