### ISSUE TITLE
Running source code in eclipse

### ISSUE THREAD

**Issue by jiangchen3512** [eclipse-chemclipse/chemclipse#274]
Hi:
 Code of https://github.com/eclipse/chemclipse.git。How to run it in eclipse? Where can I find relevant documents?
Thanks！
Mr.Jiang

**Comment by laeubi** [comment]
Hi @jiangchen3512 
Please see the Wiki https://github.com/eclipse/chemclipse/wiki/Chemclipse-Developer-Manual

Also note that there is a [mailinglist](https://dev.eclipse.org/mailman/listinfo/chemclipse-dev) for asking questions and getting guidance, the bug-tracker is not meant for asking questions.

**Comment by eselmeister** [comment]
@laeubi ChemClipse is not visible inside of an Eclipse IDE, as we still use an own "Application.e4xmi" model. We already have discussed plans and made some test to use the "org.eclipse.e4.legacy.ide.application" instead. This would make it possible to use ChemClipse as an Eclipse extension.

**Comment by jiangchen3512** [comment]
Thanks
