### ISSUE TITLE
Remove JavaFX dependencies

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#281]
The PCA tools are using JavaFX. As it turned out, mixing SWT and JavaFX works, but leads to problems in the UI thread. Moreover, the upgrade to Java 9, 10, 11, 12 wasn't possible, as there were problems with JavaFX and GTK3. JavaFX, GTK3 and Java13 seem to work. But the usage of JavaFX in ChemClipse shall be removed to keep the system maintainable.

**Comment by eselmeister** [comment]
I have created a branch called "StripJavaFX".

**Comment by eselmeister** [comment]
This is a duplicate of:
https://github.com/eclipse/chemclipse/issues/281

**Comment by laeubi** [comment]
I assume you mean #8 as duplicate as a ticket can merely duplicate itself ;-)

**Comment by eselmeister** [comment]
Yep, my mistake. #8 was the original issue.
