### ISSUE TITLE
Extract/re-insert matrix from MSD chromatogram

### ISSUE THREAD

**Issue by lorenzgerber** [eclipse-chemclipse/chemclipse#282]
Currently, available MSD chromatogram data accessors (eg. extractedIonSignal) allow only extraction of objects where the abundances are stored per scan. 

It would be useful to have a direct method for the task of extracting and re-inserting the main data matrix (abundances per time(scan) and mz(ion)) of a MSD chromatogram.

Such a method would be beneficial for many signal processing algorithms that need direct access to either the signal along the time dimension or on the whole matrix at once.

**Comment by laeubi** [comment]
@lorenzgerber  Thanks for contributing.
