### ISSUE TITLE
interpolate signal abundances for ions with zero abundance

### ISSUE THREAD

**Issue by lorenzgerber** [eclipse-chemclipse/chemclipse#289]
Control software of some instruments allows setting minimum signal abundance threshold for recoding data. Abundances below this threshold are cut off. However, for some data/signal processing methods, it would be desirable to have a continuous signal.

A chromatogram filter/processor should be implemented that iterates over all ion channels and linear interpolates abundance values for ions with zero abundance.

**Comment by laeubi** [comment]
Is this fixed now or are there any tasks left?

**Comment by lorenzgerber** [comment]
Fixed for the moment
