### ISSUE TITLE
Improve Speed: Mass Spectrum Comparison (Cosine)

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#311]
Currently, 4 comparisons are performed when doing a match of 2 mass spectra:

- Match Factor (MF)
- Reverse Match Factor (RMF)
- Match Factor Direct (MFD)
- Reverse Match Factor Direct (RMFD)

Each comparison is time consuming. The speed to do a match could be increased if comparisons are skipped if the final result is below the expectations. Hence, match constraints shall be introduced, to make a hint for the comparison algorithm. Match factors are valid in a range between 0 (no match) and 1 (perfect match):

Min MF: 0.7
Min RMF: 0.7

If e.g. the match factor is 0.699, then the calculation of RMF, MFD and RMFD can be skipped. This helps to speed up the comparison by skipping unnecessary calculations.

**Comment by laeubi** [comment]
Cosine already computes the values lazily, so it could be handled easily on the callers level.

First fetch and compare MF, ... then fetch and compare RMF ... and so on (if desired).

**Comment by eselmeister** [comment]
That's correct, but all 4 values are calculated. Using the match constraint, some calculations can be skipped.

```
Improved comparison with MatchConstraints
237 unknown against 267376 reference mass spectra:
Cosine: 232380 [ms]
Commecial DB: 253294 [ms]
```

The MatchConstraint has a default constructor, which sets the min values to 0. This enables a behavior as it was before without having match constraints.
