### ISSUE TITLE
AbstractChromatogram#equals/hascode produces weird results

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#319]
Currently AbstractChromatogram is implemented in a way that if the number of scans, the start and stop retentionTime and the max-signal are equal they are considered equal.

This produces strange results if one puts similar chromatograms into collections that uses hashCode/equals to distinguish objects.

We should instead use the standard hascode/equals method that uses the object identity, if one needs a special "equal" consideration to e.g. filter possible duplicate, a custom comparator would be more suitable.

@eselmeister WDYT? Any objections?

**Comment by eselmeister** [comment]
@laeubi Principally, yes we can change it. Before doing it, please list here where the chromatogram equals method is used in the platform. After going through this list and discussing possible bottlenecks, you can make a first change. Please run and test the application intensively. You should have test data at hand to do this.

**Comment by eselmeister** [comment]
@laeubi How is the status here?

**Comment by eselmeister** [comment]
Comments?
