### ISSUE TITLE
Adjust Build Process

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#344]
The current build process is not optimal, as download bundles are created for each integration branch. Hence, the build shall be reorganized, e.g. similar to the Eclipse SWTChart build hierarchy.

- integration (contains all branches)
- releases (contains the official releases)

We should regularly track the following page(s) and keep the footprint of ChemClipse as small as possible: 

[https://download.eclipse.org/oomph/archive/eclipse/index.html](https://download.eclipse.org/oomph/archive/eclipse/index.html)
[https://download.eclipse.org/oomph/archive/eclipse/chemclipse/index.html](https://download.eclipse.org/oomph/archive/eclipse/chemclipse/index.html)

**Comment by eselmeister** [comment]
That's too heavy. It's not required that compilations are created for all branches. Furthermore, most of the branches are not needed anymore.

![Bildschirmfoto von 2020-05-09 08-55-05](https://user-images.githubusercontent.com/686671/81466776-72013f00-91d4-11ea-8a30-b94b13caa260.png)
![Bildschirmfoto von 2020-05-09 08-55-12](https://user-images.githubusercontent.com/686671/81466777-73326c00-91d4-11ea-9389-42766d7947ff.png)

Currently, I'm cleaning this up.

After cleanup, the folder "integration" contains all integration builds of the branches. A repository is created for downstream builds. Copying the compilations is disabled. It shall be only enabled, as soon as a release is scheduled.

The folder "releases" contains the official released compilations. Files shall be copied manually and after review to the releases folder. So it is safe and can't be deleted accidentally by the build process.

**Comment by laeubi** [comment]
You can easily clean this up by scheduling a "clean build" that will remove old artifacts for the develop branch.

**Comment by eselmeister** [comment]
Yes and no. That's only possible for the current branch. First of all, the build and download directory needs to be cleaned up.

**Comment by eselmeister** [comment]
The develop branch has been cleaned up. All other branches need to be cleaned too or deleted if they are not needed any longer. I'll take care of it.

**Comment by eselmeister** [comment]
The build has been refactored successfully.
