### ISSUE TITLE
StringSettingsProperty Never Validates if regExp is ""

### ISSUE THREAD

**Issue by kerner1000** [eclipse-chemclipse/chemclipse#36]
If the regex is empty, the property does not validate.

**Comment by laeubi** [comment]
What should it validate? an empty regexp makes no sense at all?

**Comment by kerner1000** [comment]
Why should an input String always be regex-validated? What if the expected input is a name or country? Do you have a regex for that?

**Comment by laeubi** [comment]
You simply don't need ANYthing for this, you must not annotate a String as "StringSettingsProperty!"

**Comment by kerner1000** [comment]
See https://github.com/eclipse/chemclipse/issues/43.
