### ISSUE TITLE
Refactor Peak/Scan Label Display Settings

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#398]
Currently, it's possible to define the visibility of peak/scan label(s). The field to be displayed can be selected as well only certain peaks/scans for display. The current implementation has the following drawbacks:

- it's hard to maintain
- the peak/scan visibility settings are persisted locally
- the code (table viewer, ...) isn't well structured
- various setting classes are used to handle the visibility
- the code is primarily written for the ChromatogramEditor
- ...

Hence, the visibility functionality need to be refactored.

**Comment by eselmeister** [comment]
The chromatogram stores the peak/scan visibility information now. The next step is to adjust the *.ocb format to persist the visibility information. It enables to share a chromatogram, which itself contains the settings. Thus, another dependency on the local system has been removed.

**Comment by eselmeister** [comment]
Additionally, the target reference wizard has been improved. It's more user-friendly now.

![Bildschirmfoto von 2020-08-13 13-31-57](https://user-images.githubusercontent.com/686671/90130251-6c366f00-dd6a-11ea-9826-536b239a3b9a.png)

**Comment by laeubi** [comment]
Also here larger code-parts are simply copied/split to new files and added with own header information, please fix the headers and restore original author-ship information see https://github.com/eclipse/chemclipse/issues/407#issuecomment-683930182
