### ISSUE TITLE
Enhance the CLI Interface with method support

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#405]
Currently the CLI Support is very limited, we can easily extend this to a general purpose interface by making the process methods available here.

The following things are needed to support this:

1. There must be a way to load one or more chromatograms into a shared context
2. There must be a way to load and execute a method using the previously loaded chromatograms
3. To support processors that require UI interaction, there should be a "GUI Mode" where the UI is started and afterwards shutdown

**Comment by eselmeister** [comment]
@laeubi The bundle name doesn't match the ChemClipse name conventions. It contains UI code, hence it should be named

- org.eclipse.chemclipse.cli.ui

instead of

- org.eclipse.chemclipse.cli

Please fix this.

**Comment by laeubi** [comment]
No further action from my side, cli has nothing to do with ui/not ui and only references necessary dependencies.

**Comment by eselmeister** [comment]
@waynebeaton 
@laeubi: Have you renamed the bundle accordingly to the ChemClipse bundle naming pattern?

**Comment by laeubi** [comment]
Feel free to take over or keep this issue open if you think anything needs to be doe here. The original issue "Enhance the CLI Interface with method support" is resolved regardless of naming of a binary artifact.

**Comment by eselmeister** [comment]
@waynebeaton 
@laeubi It's not an issue of the binary artifact, but of the consistency of the bundle naming. If a bundle contains at least one UI dependency (SWT or other), then "ui" should be included in the bundle name, see:

- org.eclipse.chemclipse.ux.extension.xxd.ui
- org.eclipse.chemclipse.xxd.converter.supplier.chemclipse.ui
- org.eclipse.chemclipse.logging.ui
- org.eclipse.chemclipse.csd.converter.ui
- ...

You are a project lead. You should be aware of it. If you haven't been aware of it yet, you know it now. Please adjust the bundle name. Thanks.

**Comment by eselmeister** [comment]
@waynebeaton 
@laeubi Christoph, are you unable or unwilling to adjust the bundle name?

**Comment by eselmeister** [comment]
OK, I understand. You are unwilling to work in a team.
