### ISSUE TITLE
Assets - Methods are placed at wrong position in the menu

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#408]
After modifying the assets (add/delete), additional methods are displayed at the wrong position. They should be placed under "User Methods":

![Bildschirmfoto von 2020-08-27 12-47-00](https://user-images.githubusercontent.com/686671/91433746-0bc42900-e864-11ea-9fcc-8a09ab457dd3.png)

![Bildschirmfoto von 2020-08-27 12-48-33](https://user-images.githubusercontent.com/686671/91433758-0ff04680-e864-11ea-862c-978e0388e757.png)

@laeubi Please add process method assets at the correct position.

**Comment by laeubi** [comment]
The method Will be placed in the category Named in the User-Method when installed via the Assetsmanager,, User-Methods only list those in the standard location. So if you need it to be placed under User-Methods anyways, simply use "User Methods" as category name.

**Comment by eselmeister** [comment]
@laeubi OK, I tried to test it. But even after removing the "Process Method" from the Assets, it's not removed from the menu. It's even not removed after closing and opening the editor.

![Bildschirmfoto von 2020-08-27 13-29-45](https://user-images.githubusercontent.com/686671/91437188-c86cb900-e869-11ea-9458-378dd8d6476d.png)

![Bildschirmfoto von 2020-08-27 13-29-49](https://user-images.githubusercontent.com/686671/91437198-cc004000-e869-11ea-9277-7631c228ee98.png)

![Bildschirmfoto von 2020-08-27 13-30-11](https://user-images.githubusercontent.com/686671/91437205-cefb3080-e869-11ea-9c6d-de692abe1451.png)

**Comment by laeubi** [comment]
I submitted a patch, please retry with that change.

**Comment by eselmeister** [comment]
@laeubi OK, the *.bak files are not recognized as normal methods any longer. But

* adding a "Process Method" via the Assets requires a restart of the application
* removing a "Process Method" via the Assets requires a restart of the application (it's still in the menu after removing it)

So is the same for "User Methods", e.g. if one modifies the methods via the method editor toolbar.

**Comment by laeubi** [comment]
If I remmber right to get rid of "flickering" / "event-storm" currently the menu is not instantly updated but only when you close/reopen the editor.

**Comment by eselmeister** [comment]
@laeubi That's why I was wondering, why you have closed the JFace menu issue yesterday?
https://github.com/eclipse/swtchart/issues/84

**Comment by laeubi** [comment]
The issue itself "Methods are placed at wrong position in the menu" is resolved as it works like intended, if anything unclear let me know.

Whether or not and how I'm contribution to swtchart is defiantly out of scope here.
