### ISSUE TITLE
SNIP Baseline correction and Savitzky-Golay Filtering for Spectra was removed

### ISSUE THREAD

**Issue by Mailaender** [eclipse-chemclipse/chemclipse#423]
https://www.researchgate.net/publication/334029427_Alternative_Software_zur_MALDI-TOF_MS_Auswertung page 29 to 31 shows the past workflow. This seems to be collateral damage of https://github.com/eclipse/chemclipse/issues/362 and should be undone.

**Comment by eselmeister** [comment]
@Mailaender I had a look at the case. You're right, that was a mistake and shouldn't happen. Thanks for your report. The toolbar menu entries have been moved to the context sensitive pop-up menu. The functionality still exists. For the MALDI editor, the pop-up menu must be extended to display the scan mass spectrum filter and identifier. I'll inspect how to populate the menu.

**Comment by Mailaender** [comment]
If you want to clear up the menu strip I suggest to start by removing the `Controls` menu which only has a placeholder in it.

**Comment by eselmeister** [comment]
@Mailaender You are right, the "Controls" menu item hasn't been used yet. Hence, I'll create a new issue to remove it.

**Comment by eselmeister** [comment]
![Bildschirmfoto von 2020-10-12 21-37-27](https://user-images.githubusercontent.com/686671/95784520-47ac3400-0cd4-11eb-8a25-53bf3fbb044a.png)

![Bildschirmfoto von 2020-10-12 21-37-38](https://user-images.githubusercontent.com/686671/95784533-4b3fbb00-0cd4-11eb-9532-606330eb3257.png)

**Comment by eselmeister** [comment]
@Mailaender This was a quick fix. There is much room for improvements. Currently, the system settings are used by default. The progress dialog is not displayed. An interactive settings page is also not displayed. For example, the settings page handling for chromatograms is located here:

`org.eclipse.chemclipse.ux.extension.xxd.ui.methods.SettingsPreferencesPage`

The settings functionality should be merged. Additionally, the code of the `SettingsPreferencesPage` needs some refactoring as the code is not well separated and completely stuffed in the `createControl(Composite parent)` method.

Let's discuss how to proceed.

**Comment by Mailaender** [comment]
This was resolved in https://github.com/eclipse-chemclipse/chemclipse/pull/2111.
