### ISSUE TITLE
Adding traces into peak trace feature

### ISSUE THREAD

**Issue by JMRoper** [eclipse-chemclipse/chemclipse#440]
I am fairly new to Openchrom, and would like to be able to change the default traces in the peak traces window/ feature to one which vary in my compounds of interest. I have found how to create my own named trace set, but am unsure of how to import those into the peak trace window and make the traces visible, my main desire is to include traces of 43 and 45 ions. Attached is my current peak trace window. Any advice or guidance would be extremely appreciated, thank you in advance! 

<img width="961" alt="Screen Shot 2020-11-11 at 9 59 51 PM" src="https://user-images.githubusercontent.com/74342128/98901796-3ab46900-2469-11eb-85d5-a9a42d0f3c6e.png">

**Comment by Mailaender** [comment]
This was added in https://github.com/eclipse/chemclipse/issues/376.

**Comment by eselmeister** [comment]
See #376

Via the "Named Traces", one can define user specific profiles to be displayed in the chromatogram overlay "SIC" modus. The peak traces part display the n highest m/z values as an SIC profile of the underlying chromatogram at the retention time range of the peak model. Via the settings, you can define the number of ions to display. The m/z values are automatically extracted, based on the peak mass spectrum. So it depends on the peak mass spectrum, if m/z 43 or 45 is available. In all other cases, we recommend to use the chromatogram overlay part with named traces.
