### ISSUE TITLE
Signals Extractor does not handle empty MSD scans

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#51]
The ion signals extractor crashes, when the extracted chromatogram range contains empty scans. Empty scans means, that no m/z value is stored, e.g. when the detector is turned to off.

A filter is available "Remove Empty Scans". This should be used in case one assumes that empty scans are contained.

Anyways, the signal extractor shall be fixed.

**Comment by lorenzgerber** [comment]
The fix still includes the first zero-signal scan. This is imho wrong as in the general case, the extraction includes data for start and stop scan. Current behaviour defeats the purpose of stopping on zero scans as it still leads to eg. array index out of bound problems etc.

**Comment by eselmeister** [comment]
Sure, it's can be discussed whether to adjust the noise segment calculator in a way that also zero scans are handled. This needs more and deeper investigations and could lead to unwanted side effects, especially when processing the extracted signals. We have a similar problem when running peak deconvolution in AMDIS. If the scan rate is too high, many false positives are detected. But the "Scan Remover" is available to reduce the scan rate.

In this case, a filter is available to remove empty scans:

![Bildschirmfoto von 2019-10-09 11-20-36](https://user-images.githubusercontent.com/686671/66469181-b7675d80-ea87-11e9-84e5-2b01ec87781e.png)

This could be applied before running the deconvolution:

![Bildschirmfoto von 2019-10-09 11-20-42](https://user-images.githubusercontent.com/686671/66469235-c9490080-ea87-11e9-8a72-62ad70543968.png)

**Comment by lorenzgerber** [comment]
ok, misunderstanding as I was not aware that scans are 1 based. Please close.
