### ISSUE TITLE
Chromatogram right-click menu immediately closes

### ISSUE THREAD

**Issue by Mailaender** [eclipse-chemclipse/chemclipse#540]
I believe this happens because the right-click triggers an update (as seen in the console) of SWT Chart which then kills the menu. If you left-click on the chart first, wait a few seconds and then right-click the menu won't immediately close.

**Comment by eselmeister** [comment]
Also have a look at this issue:
https://github.com/eclipse/swtchart/issues/84

First of all, we should perform some further investigations to understand the problem.

**Comment by Mailaender** [comment]
I narrowed it down already: close the Targets part and the problem is greatly reduced (but not completely gone). Add some logging and the madness reveals itself. There is an event loop between Targets and Chromatogram which fires a handful of events that take several seconds to process and they contain no actually changed items.

I also investigated https://github.com/eclipse/swtchart/issues/84. It rebuilds the menu on update but removing the update on the menu manager (and only having a default SWT Chart menu) did not improve the situation at all. Also note that no other part shows that behavior. You can right-click on a scan chart and it won't close your context menu right away.

**Comment by eselmeister** [comment]
See also:
https://github.com/eclipse/swtchart/issues/243
