### ISSUE TITLE
Clicking cancel on a NIST search has little to no effect

### ISSUE THREAD

**Issue by Mailaender** [eclipse-chemclipse/chemclipse#566]
![image](https://user-images.githubusercontent.com/756669/114683855-aba9c680-9d10-11eb-8520-9d9e9d70f054.png)

**Comment by eselmeister** [comment]
@Mailaender The monitor shall be checked regularly if cancel is pressed. If cancel has been pressed, the clean methods must be called to leave a clean status.

```
/*
 * Clean temporary files finally to not pollute the workspace for other
 * applications.
 */
resetPeakIdentifier(peaks, identifierTable);
cleanFiles(runtimeSupport, monitor);
restoreControlFiles(runtimeSupport);
```

or

```
/*
 * Clean temporary files finally to not pollute the workspace for other
 * applications.
 */
resetMassSpectrumIdentifier(massSpectrumList, identifierTable);
cleanFiles(runtimeSupport, monitor);
restoreControlFiles(runtimeSupport);
```

**Comment by Mailaender** [comment]
It seems that it does not react only for the first few seconds. After that, the dialog becomes responsive.
