### ISSUE TITLE
Chromatogram Overlay - Add Ruler Support

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#572]
Sometimes, it is useful to determine the distance between two peaks.

**Comment by eselmeister** [comment]
![Bildschirmfoto von 2021-04-19 12-21-59](https://user-images.githubusercontent.com/686671/115221905-70413a80-a10a-11eb-94be-5bffc1e1a22c.png)

Press CTRL + left mouse button and draw a line.

![Bildschirmfoto von 2021-04-19 12-22-15](https://user-images.githubusercontent.com/686671/115221980-851dce00-a10a-11eb-9985-f35ac0017985.png)

The result is displayed in the toolbar.

![Bildschirmfoto von 2021-04-19 12-22-32](https://user-images.githubusercontent.com/686671/115222028-9535ad80-a10a-11eb-9278-d408ad253430.png)

**Comment by fieldofnodes** [comment]
Cool feature.

Could this be used in the comparison with chromatograms from different machines?

I assume the time for each peak would be the argmax time for a given peak?

How is the distance calculated? 
1. Absolute value: |(Time_2  - Time_1)| 
2. Euclidean distance: |(Time_1,Intensity_1) - (Time_1,Intensity_1)| in the plane?

**Comment by eselmeister** [comment]
@fieldofnodes Yep, it can be used to calculate the time difference of e.g. the same peak from different chromatograms. The chromatogram overlay displays the TIC, XIC, SIC ... of all open chromatogram editors.

The time, intensity delta is calculated as is. See `ChromatogramRulerChart`:

```
	private void calculateDimension(Event event) {

		BaseChart baseChart = getBaseChart();
		IAxisSet axisSet = baseChart.getAxisSet();
		Point rectangle = baseChart.getPlotArea().getSize();
		int width = rectangle.x;
		int height = rectangle.y;
		//
		if(rulerUpdateNotifier != null) {
			if(width != 0) {
				/*
				 * X (Retention Time)
				 */
				double factorWidth = 100.0d / width;
				double percentageStartWidth = (factorWidth * xStart) / 100.0d;
				double percentageStopWidth = (factorWidth * xStop) / 100.0d;
				//
				IAxis retentionTime = axisSet.getXAxis(BaseChart.ID_PRIMARY_X_AXIS);
				Range millisecondsRange = retentionTime.getRange();
				double millisecondsWidth = millisecondsRange.upper - millisecondsRange.lower;
				double startX = millisecondsRange.lower + millisecondsWidth * percentageStartWidth;
				double stopX = millisecondsRange.lower + millisecondsWidth * percentageStopWidth;
				/*
				 * Y (Intensity)
				 */
				double startY = 0.0d;
				double stopY = 0.0d;
				if(height != 0) {
					IAxis intensity = baseChart.getAxisSet().getYAxis(BaseChart.ID_PRIMARY_Y_AXIS);
					Range intensityRange = intensity.getRange();
					double abundanceHeight = intensityRange.upper - intensityRange.lower;
					double factorHeight = 100.0d / height;
					double percentageStartHeight = (100.0d - (factorHeight * yStart)) / 100.0d;
					double percentageStopHeight = (100.0d - (factorHeight * yStop)) / 100.0d;
					//
					startY = (float)(intensityRange.lower + abundanceHeight * percentageStartHeight);
					stopY = (float)(intensityRange.lower + abundanceHeight * percentageStopHeight);
				}
				/*
				 * Fire an update.
				 */
				rulerUpdateNotifier.update(new RulerEvent(startX, stopX, startY, stopY));
			}
		}
	}
```

And the delta in the `RulerEvent`:

```
	public double getDeltaX() {

		return stopX - startX;
	}

	public double getDeltaY() {

		return stopY - startY;
	}
```
