### ISSUE TITLE
Closing the PCA editor does not unload data

### ISSUE THREAD

**Issue by Mailaender** [eclipse-chemclipse/chemclipse#599]
Even a small data set accounts for ~1 GB of RAM.

**Comment by eselmeister** [comment]
@Mailaender Probably, some references can be removed during the process as they aren't needed.

**Comment by Mailaender** [comment]
This is a larger scale problem in the platform: every `AbstractPart` will leak data and reload when focussed again.

![image](https://user-images.githubusercontent.com/756669/137473199-0f165d8d-7060-410a-800f-3bea8d42469d.png)
