### ISSUE TITLE
Deprecated AbstractChromatogramClassifier constructor defaults to MSD datatype only

### ISSUE THREAD

**Issue by lorenzgerber** [eclipse-chemclipse/chemclipse#614]
The deprecated AbstractChromatogramClassifier constructor defaults to DataType.MSD which prevents classifiers that extend AbstractChromatogramClassifier and work both in MSD and WSD from showing up in WSD chromatograms.

**Comment by laeubi** [comment]
> The deprecated AbstractChromatogramClassifier constructor defaults to DataType.MSD

That's why its deprecated

>  which prevents classifiers that extend AbstractChromatogramClassifier

extensions should override the default constructor and call the specific `super(... supported datatypes list ...)`

**Comment by lorenzgerber** [comment]
Ah right, thanks Christoph. I adjusted it in my plugin.
