### ISSUE TITLE
If a processor implements ProcessEntryContainer then it should be executed

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#63]
Processors might supply processing entries (e.g. a Method-Processor) and should then be executed first (if applicable) and then its child entries.

**Comment by kerner1000** [comment]
Can you explain into more detail what the problem is?

**Comment by laeubi** [comment]
This is not a problem but an improvement to reduce possible code duplication and to unify execution of process methods.
