### ISSUE TITLE
Update to Java 11

### ISSUE THREAD

**Issue by Mailaender** [eclipse-chemclipse/chemclipse#687]
Java 8 is deprecated. The current LTS release is 11. https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by Mailaender** [comment]
We can also update https://wiki.eclipse.org/Tycho/Release_Notes/2.0#Requires_Java_11 then.

**Comment by eselmeister** [comment]
Yeah, good idea. I can't wait to upgrade to Java 11.
