### ISSUE TITLE
Import reference chromatograms default popup window size is too small

### ISSUE THREAD

**Issue by Mailaender** [eclipse-chemclipse/chemclipse#745]
![Screenshot_20210917_111725](https://user-images.githubusercontent.com/756669/133758836-4b89e5a4-af8a-4ca0-b98d-490d4c73f83c.png)

**Comment by eselmeister** [comment]
Yep

**Comment by Mailaender** [comment]
It is still too small if you have high DPI settings:

![image](https://user-images.githubusercontent.com/756669/135817446-d276218d-2c7f-4fe8-8671-58e884d34d8a.png)

Proper fix would be to have a responsive layout.
