### ISSUE TITLE
Regular expressions are displayed to the users

### ISSUE THREAD

**Issue by Mailaender** [eclipse-chemclipse/chemclipse#780]
Not everyone will be a regex ninja so maybe this should be translated into user friendly instructions again:

![image](https://user-images.githubusercontent.com/756669/137166956-9a713578-ad43-47cc-b85d-e5937c470436.png)

**Comment by eselmeister** [comment]
Probably, most users have not read the following book yet:
https://www.google.de/books/edition/Regul%C3%A4re_Ausdr%C3%BCcke/ZBOuAgAAQBAJ?hl=de&gbpv=1&printsec=frontcover
