### ISSUE TITLE
Peak/Scan List, Bug in selection/highlighting selected row

### ISSUE THREAD

**Issue by lorenzgerber** [eclipse-chemclipse/chemclipse#813]
If the Peak/Scan List contains both Scan and Peaks entries, selecting a Peak entry by mouse will at the same time also highlight a scan entry.

![Screenshot 2021-11-18 at 15 56 15](https://user-images.githubusercontent.com/3002206/142439338-0efc0278-eef9-4138-abb5-ddca38ddcbf1.png)
.

**Comment by eselmeister** [comment]
@lorenzgerber Thanks for reporting. @Mailaender Can you reproduce this behavior?

**Comment by Mailaender** [comment]
Yes and I also started experimenting. I am not sure how to proceed yet as I don't know how much of this is actually wanted behavior. See the 4 different settings to turn it off and the editor which also shows peaks and scan separately.
