### ISSUE TITLE
Methods embedded in bundles should be discovered

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#82]
Currently it is possible to use user-methods as processors. This is currently bound to the users locally stored methods, intentionally we don't restrict the usage of this methods e.g. they can be copied/modified as one likes but on the other hand also has intended restrictions, e.g. are placed always in the User-Methods Category and can't be configured on the fly.

We should now extends this approach in a way that allows software modules to embed a method definition inside a bundle to define a so called "Meta-Processor" that means a specialized method that combines several smaller processing steps.
These methods should behave a little bit different than the user methods in the following way

- they can't be copied and are (from a users perspective) are read only items that behave like any other (java based) processor
- their category is used to place them in the corresponding menu category (e.g in the Chromatogram Editor)
- if the method is final, then it behaves like a processor without a configuration
- if it is not final, it would be possible to configure the different processing steps but don't change order or add/remove items

This is especially useful in the area of NMR, where a transformation e.g. from FID -> Spectra involves many intermediate steps, but for the common use-case a fixed set of steps.
But also for peak detectors this might be interesting, e.g. if a given peak-detector could  benefit from a given preprocessing to improve the the overall detection quality it would be possible to offer that to the user without the need to implement a new processor, duplicate code-calls and configuration options.

**Comment by kerner1000** [comment]
What is the advantage over defining meta processors programatically inside bundles?
If we define (meta-)processors as files inside a bundle, we do not have less code, but just other, non-java code, which might increase overall complexity. I am thinking for example of API changes in the processing API. If we define processors programmatically, those changes lead to easily detectable compile errors. If processors are defined via files, those changes will lead to runtime errors.
Furthermore, files might be copied around and you loose access to them. That means, backward-compatibility to files, that have been created with an older version of the API, needs to be guaranteed, which might introduce a significant overhead.

**Comment by laeubi** [comment]
Backward-Compatibilty of Method File-Formats is already implemented/guranteed, the required code to define those in java code is much more complex and. And why should one "copy around" files? You won't copy around Manifest.MF or coponent.xml or icons either.
If we break it for this use-case we also break it for the users and it must be fixed then.

**Comment by kerner1000** [comment]
What about compile vs. runtime errors?

**Comment by laeubi** [comment]
Its the other way round: If we change processing API, we need to adjust method reader accordingly, as well as code using it (maybe this feature is the affected and need to be adjusted), so there won't be any runtime error at all and no need to change anything beside the core classes.
If we implement it 10 times (most probably across different projects/modules), and change API then there will be 10 places to adjust the API even outside of ChemClipse.
