### ISSUE TITLE
Decoration fails for the search case sensitive button

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#832]
Somehow, the decoration is not set. The gif shall be used instead of the png file, see:
https://github.com/eclipse/chemclipse/commit/577382e31b8bae6e307fe9b14402ff26fc704045

**Comment by eselmeister** [comment]
![Bildschirmfoto von 2021-12-02 11-18-19](https://user-images.githubusercontent.com/686671/144402998-4ef7682f-4d57-4613-905a-9a983b0bbe67.png)

![Bildschirmfoto von 2021-12-02 11-18-23](https://user-images.githubusercontent.com/686671/144403014-a0b5d4db-cac1-48c1-9668-a523371c441f.png)

**Comment by Mailaender** [comment]
It even caused the warning again which should have told me.
```
WARN  main core.ApplicationImage.lambda$0 (ApplicationImage.java:77) java.util.concurrent.TimeoutException
WARN  main core.ApplicationImage.lambda$0 (ApplicationImage.java:78) The decoration for the following icon fails: org.eclipse.chemclipse.rcp.ui.icons/caseSensitive.png
WARN  main core.ApplicationImage.lambda$0 (ApplicationImage.java:79) Please check the icon. Is it a png? Does it contain an embedded RGB profile?
WARN  main core.ApplicationImage.lambda$0 (ApplicationImage.java:80) Solution: Probably try to convert the icon to *.gif format.
```
