### ISSUE TITLE
Process Method Editor - enable user specific process entry description

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#861]
It's possible to create user specific process methods. For a better readability the user shall be enabled to set a specific process entry description if possible.

**Comment by eselmeister** [comment]
![Bildschirmfoto von 2022-01-06 07-57-25](https://user-images.githubusercontent.com/686671/148342418-2091095c-113a-47b2-a80c-45771b46a929.png)

![Bildschirmfoto von 2022-01-06 07-57-55](https://user-images.githubusercontent.com/686671/148342421-5740e02d-cf76-465b-bb82-c367d7f07074.png)

![Bildschirmfoto von 2022-01-06 07-58-02](https://user-images.githubusercontent.com/686671/148342423-a4aea86f-b0a1-4350-9d9e-fbdbe30dc362.png)

![Bildschirmfoto von 2022-01-06 07-59-09](https://user-images.githubusercontent.com/686671/148342425-0e8bab87-0ffe-49b7-a3a8-c77ee4a3eb95.png)

**Comment by Mailaender** [comment]
This is a reverse duplicate of https://github.com/eclipse/chemclipse/issues/108.
