### ISSUE TITLE
Peak/Scan List does not update on opening a new chromatogram

### ISSUE THREAD

**Issue by lorenzgerber** [eclipse-chemclipse/chemclipse#912]
The content of the Peak/Scan List does not update when one chromatogram is currently active and a new one is loaded. 

tested cases (on OSX):
- active ch contains no peaks, new chromatogram contains peaks -> peaks new ch not shown until switch back/forth between the two ch
- active ch contains peaks, new chromatogram contains no peaks -> peaks from old ch still visible until switch back/forth between the two ch
- active ch contains peaks, new chromatogram contains peaks -> peaks from old ch still visible until switch back/forth between the two ch

**Comment by Mailaender** [comment]
This also happens on Linux, so I guess it is platform unrelated. Clicking Data Explorer to open a new chromatogram and then Peak/Scan List unfocuses the editor, it needs to be clicked again to force an update which is one click too much.

**Comment by Mailaender** [comment]
The underlying problem is that parts don't listen for updates while they are hidden.
