### ISSUE TITLE
Peak/Scan List not updated automatically from Scan Identifiers, Peak Detector

### ISSUE THREAD

**Issue by lorenzgerber** [eclipse-chemclipse/chemclipse#918]
Currently, when a Scan Identifier or Peak Detector is run, while the Peak/Scan List is already open (independent whether it's currently visible or not) the Peak/Scan List is not updated. A manual press to the 'Reset Peak/Scan List' is required to visualise the Peaks/Scans in the List.

Requested behaviour would be that running an above operations will update the Peak/Scan List, ideally independent from whether it's currently visible or not. Having a GUI application, it feels counter intuitive that you have to press a reset button to obtain data. If there is no way to solve it, I suggest that 'update data' button would be a better name.

Tested on OSX, both on MSD and WSD chromatogram

Note that this is different from #913 which now works (opening/closing a chromatogram will fire an update on the Peak/Scan List).

**Comment by Mailaender** [comment]
Right-click chromatogram peak detection works fine for me. However, scan identifiers never update no matter from where it is set.

**Comment by lorenzgerber** [comment]
ok, works for MSD, but still not for WSD

**Comment by Mailaender** [comment]
> ok, works for MSD, but still not for WSD

It also works for WSD, when using 1st derivative peak detector.

Add dirty handling to yours https://github.com/eclipse/chemclipse/commit/b6b870301f475ec3eaa6a8212d81945b016c0c29#diff-ac58f193737f030e7e04e24ddc7e5444e117ebafb0ce1b9159074bfc21e80d61 and it should solve the peak/scan list not updating.

For peak detection, this may want to be handled at a higher level in the future.
