### ISSUE TITLE
Support to subtract one chromatogram from another

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#93]

**Comment by eselmeister** [comment]
A method was requested to subtract one chromatogram from another. The first implementation could be really simple. it's just needed that the TIC from one chromatogram is subtracted from another chromatogram, regardless whether it is MSD, CSD or WSD. The MSD chromatogram should be handled in a separate way in the case that the adjusted total signal is <= 0. If that happens, the resulting scan shall be empty.

**Comment by eselmeister** [comment]
![Bildschirmfoto von 2019-10-23 16-55-56](https://user-images.githubusercontent.com/686671/67406551-83775680-f5b6-11e9-872e-281d469a8617.png)
![Bildschirmfoto von 2019-10-23 16-56-04](https://user-images.githubusercontent.com/686671/67406563-86724700-f5b6-11e9-9db7-8779e8b4602b.png)
![Bildschirmfoto von 2019-10-23 16-56-20](https://user-images.githubusercontent.com/686671/67406617-9427cc80-f5b6-11e9-9e7e-e03a035156d9.png)
![Bildschirmfoto von 2019-10-23 16-56-39](https://user-images.githubusercontent.com/686671/67406640-9be77100-f5b6-11e9-8cb6-6a8dd2fd2cb2.png)
![Bildschirmfoto von 2019-10-23 16-56-48](https://user-images.githubusercontent.com/686671/67406662-a43fac00-f5b6-11e9-9ee1-0b1eaba8f15a.png)

**Comment by eselmeister** [comment]
I don't know why the issue is not closed. Maybe there must be a white space between "Fix" and issue id. Here's the change:
https://github.com/eclipse/chemclipse/commit/33d42aa71176dc945ba6457217bd78a4849c4f13

**Comment by laeubi** [comment]
@eselmeister see https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords for all supported kewords/formats.

**Comment by eselmeister** [comment]
ThanksAm 23.10.2019 18:43 schrieb Christoph Läubrich <notifications@github.com>:@eselmeister see https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords for all supported kewords/formats.
