### ISSUE TITLE
Chromatogram Batch Process - CSD fails

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#96]
The chromatogram batch process seems to be broken when trying to process CSD files. The batch process works well for MSD, but when using CSD files, the following error occurs:

![Bildschirmfoto von 2019-10-23 21-02-15](https://user-images.githubusercontent.com/686671/67425516-6f445100-f5d8-11e9-85c5-810e7dc1fd5c.png)

Could it be, that the converter does not recognize the file type of the processed chromatograms?

**Comment by laeubi** [comment]
This most probably means the converter can't read the file, can you provide a test-file that shows the problem? I'll take a look at it then.

**Comment by laeubi** [comment]
The problem was that only the file extension was checked, but not the magic code. If the fileextension matches different types (eg. CSD or MSD) then always msd is choosen.

**Comment by eselmeister** [comment]
All right, thanks. It works now.
