### ISSUE TITLE
Provide Export Chart Selection Processor for Chromatograms

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#98]
Currently it is possible to choose "Export Chart" to various formats with the context menü. But this is not available for the Batch/Processmethods.

There should be a processor in the "Chromatogram Export" category that has a setting for choosing the format to use (e.g. png/pdf/...).

This for example allows to save the final or intermediate steps into an image for reporting.

**Comment by eselmeister** [comment]
Principally, all SWTCharts can be exported to various formats. SWTChart itself defines the export options. in ChemClipse, domain specific charts are used, extended from basic SWTChart Line-, Scatter- or BarChart. In a report, one could not only need the chromatogram as a chart itself but also a list of peaks and mass spectra. So, we should consider to export:

- Chromatogram
- Peak(s)
- Scan(s) - MSD/WSD; CSD is probably not so important as the former ones
- NMR Record
- FTIR Record

We probably do not need support for all types at the beginning, but we should keep a generic approach in mind. A drawback of this approach is, that a GUI must be available to create the image export. There is a generic chart for chromatograms, which is used for some processors and which could be also used to create a bitmap export for chromatograms:

**org.eclipse.chemclipse.ux.extension.xxd.ui.charts.ChromatogramChart**

A working example exists to create chromatogram charts in OpenChrom:

**net.openchrom.msd.converter.supplier.pdf.ui.converter.ReportPDF**
