### ISSUE TITLE
Feature request for command line file converter

### ISSUE THREAD

**Issue by ethanbass** [eclipse-chemclipse/chemclipse#985]
I don't know if this is outside the scope of the project, but it would be great to just have a command-line interface to convert MS files using the chemclipse parsers.

**Comment by Mailaender** [comment]
There already is https://github.com/OpenChrom/openchrom/wiki/CLI however as ChemClipse does not include proprietary vendor file format parsers you should https://lablicate.com/platform/openchrom/download instead.

**Comment by ethanbass** [comment]
Thank you!
