### ISSUE TITLE
Provide "Open in Editor" Processor

### ISSUE THREAD

**Issue by laeubi** [eclipse-chemclipse/chemclipse#99]
Currently one could save a chromatogram to a file, but sometimes it is more feasible to show it inside an editor. That way it is possible to batch process a list of files and then review them in an editor instead of saving to disk and the have to open manually.

**Comment by eselmeister** [comment]
There is an example to show an "editor" UI in the following OpenChrom peak detector ""Template Peak Detector UI (MSD)".

net.openchrom.xxd.process.supplier.templates.ui.core.PeakDetectorMSD

The template peak detector uses a basic chart from ChemClipse:
```
public class PeakDetectorChart extends ChromatogramChart {

}
```

The peak detector UI also can be used in a process method, but only if a UI is available. The drawback is, that a use interaction is required. The batch process is halted until the user clicks on "Finish" to close the dialog.
