### ISSUE TITLE
Console is not displayed in 'Data Analysis' perspective

### ISSUE THREAD

**Issue by eselmeister** [eclipse-chemclipse/chemclipse#993]
An compatibility view error is thrown and the console part is empty.

**Comment by Mailaender** [comment]
Reverse duplicate of https://github.com/eclipse/chemclipse/issues/979.

**Comment by eselmeister** [comment]
![Screenshot from 2022-03-31 08-13-22](https://user-images.githubusercontent.com/686671/160988612-daf8e9cc-9500-4b6c-b663-94c51f9801f0.png)

**Comment by eselmeister** [comment]
@Mailaender Ah yes, good point. Thanks for the hint.
